version: '3'

services:
  postgres:
    container_name: shoppingcart-postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=thepassword
    volumes:
      - ./db/data:/docker-entrypoint-initdb.d