version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: api-docker-debug
    ports:
      - "9050:9050"
    depends_on:
      - postgres

  postgres:
    container_name: shoppingcart-postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=thepassword
    volumes:
      - ./db/data:/docker-entrypoint-initdb.d